### ISSUE TITLE
Missing priest interrupt spell 

### ISSUE THREAD

**Issue by nanjuekaien1** [Nitrak/Vocal-Raid-Assistant#105]
Missing priest interrupt spell 
ID：15487

P:Party gives me spell [Power Infusion] no voice

**Comment by nyy23** [comment]
good catch on the priest interrupt. 

PI is not announced when cast on an party member? 
This might be intentional - can you check if "Only on me" is enabled in "General" Settings.

**Comment by nanjuekaien1** [comment]
Enable “Only externals on you”

**Comment by nyy23** [comment]
Reopening:
Adressing "Priest interrupt not working".
