### ISSUE TITLE
Add multi-language voice-packs

### ISSUE THREAD

**Issue by Nitrak** [Nitrak/Vocal-Raid-Assistant#109]
First focus:

German
Chinese
Russian

**Comment by nanjuekaien1** [comment]
About the Chinese voice pack.
They still hope to generate a Chinese voice document for publication as soon as possible (even if it is an empty document), and they can add their own voice files to the Chinese voice package. Because there are now four Chinese voice packs in the Chinese region.

**Comment by Nitrak** [comment]
Hi @nanjuekaien1,

We are close to making stand-alone voice-pack addons functional. Just finishing some last stuff. Soon you can maintain your own Chinese Voice Package! Horray :D

**Comment by Nitrak** [comment]
@nanjuekaien1 you can now upload your own addon in the same style as https://www.curseforge.com/wow/addons/vocal-raid-assistant-ana-sound-pack to support Chinese voices!
Look at how the addon is set up and you should be able to get your own to work easily!

If you want the addon more easily found name it something like:
Vocal Raid Assistant - <Name> Sound Pack [zhCN]
