### ISSUE TITLE
Track important trinket usage

### ISSUE THREAD

**Issue by Nitrak** [Nitrak/Vocal-Raid-Assistant#11]
Track important trinket usage from for example tanks. Look at OmniCD for an idea of what trinkets are important.

**Comment by 5chmidt** [comment]
The tank trinkets that are important:
Splintered Heart of Al'ar (does not have a cast instead you get a debuff when it triggers).
https://www.warcraftlogs.com/reports/wJCd1XnMvqHxk2Ly#fight=4&type=auras&source=4&spells=debuffs

Blood Spattered Scale: cast id=329840
https://www.warcraftlogs.com/reports/nWfTNHhjFxAtvDBg#fight=14&type=casts&source=2

Shard of Annhylde's Aegis: cast id=358712
https://www.warcraftlogs.com/reports/nWfTNHhjFxAtvDBg#fight=14&type=casts&source=2&ability=358712

There are probably some PvP trinkets worth tracking too.

**Comment by nyy23** [comment]
+1 for mentioning Splinterd Heart

Trinket proccs are usually just forcing your char to cast a 'hidden' spell. As long as we have the spell id for this hidden spell, we should be able to announce it.

Should be one of this: https://www.wowhead.com/spell=344900 or https://www.wowhead.com/spell=344907
Will have to test it.
