### ISSUE TITLE
Only announce when in range [Default: Off]

### ISSUE THREAD

**Issue by Nitrak** [Nitrak/Vocal-Raid-Assistant#141]
Thinking about if it would ever make sense to only hear abilities when cast in range.

By default, this should definitely be off. What do you think @nyy23?

**Comment by Nitrak** [comment]
Can use this [library](https://www.wowace.com/projects/librangecheck-2-0/pages/api) and check caster of spell <=40 on either min or max return.

**Comment by nyy23** [comment]
I would be really careful when implementing this. There is already a lot of checks going on, so this might be performance critical

**Comment by Nitrak** [comment]
> I would be really careful when implementing this. There is already a lot of checks going on, so this might be performance critical

It would be one additional check for each spell cast. Unitframe addons use this call for each frame for each player in the raid. But it would for sure be a feature that should be tested in a Mythic Raid setting before any release. But I think it would not cause any additional performance loss. And with the feature turned off it should be as if it never existed.
