### ISSUE TITLE
Dancing Rune Weapon  

### ISSUE THREAD

**Issue by nanjuekaien1** [Nitrak/Vocal-Raid-Assistant#171]
DEATHKNIGHT

Voice for Dancing Rune Weapon not working

**Comment by Nitrak** [comment]
Which Sound Pack are you using and what version of WoW?

I see 49028 is added in Julie and the spell list.

**Comment by nanjuekaien1** [comment]
Version: 2.5.0
COVENANTS,  317009  doesn't work either
The voice package was recorded by me looking for a Chinese player,
Clicking on the interface can prompt, but it does not work in battle.

**Comment by Nitrak** [comment]
@nyy23 can you look into it when you have time?

**Comment by nanjuekaien1** [comment]
Seems like none of the skills cast on the target are working.

**Comment by nyy23** [comment]
>COVENANTS, 317009 doesn't work either
Working as expected.

If you have selected "combat only" it will only play spells when **you** are actually in combat.
-> During pull situation, there is a short delay where your Tank is in combat, while you are not. You will not hear spells cast in that short time period. Same applies for spells, that are precast.

Solution: Disable "combat only"

**Comment by nanjuekaien1** [comment]
combat only is not enabled

**Comment by nyy23** [comment]
@nanjuekaien1 
I`m still not able to reproduce the issue. Can you share your config?

**Comment by nanjuekaien1** [comment]
^1^T^S2825^B^S198589^B^S1022^b^S322109^b^S116849^b^S328231^b^S12975^b^S115310^b^S58984^B^S178207^B^S108199^b^S187827^B^S19577^b^S32375^b^S80353^B^S8122^b^S51514^b^S6940^b^S320674^b^S205369^b^S31821^b^S97462^b^S114052^b^S88625^b^S192058^b^S217832^B^S323673^b^S61999^b^S111771^b^S191427^B^S16191^b^S316958^b^S115078^b^S196718^B^S29166^b^S118^b^S30283^b^S179057^B^S871^b^S265202^b^S64843^b^S740^b^S10060^B^S102342^b^S49576^b^S86949^b^S326860^b^S109964^b^S78675^b^S13750^b^S108280^b^S325013^b^S62618^b^S310454^b^S64901^b^S193530^b^S246287^b^S48707^b^S51052^b^S106898^B^S207167^b^S2094^b^S19801^b^S61336^b^S324386^b^S98008^b^S190319^b^S323764^b^S77761^b^S116844^b^S23920^b^S212084^B^S33206^b^S32182^B^S22812^b^S77764^B^S642^b^S73325^b^S187650^b^S317009^B^S64044^b^S196555^B^S109248^b^t^^

**Comment by Nitrak** [comment]
@nanjuekaien1 that is an export of your your area setup, not the config file. (Also, this does not have Dancing Rune Weapon enabled).
<img width="343" alt="image" src="https://user-images.githubusercontent.com/10738716/190870681-d995b66f-a3a9-4a2d-9e72-0867844bd384.png">


Your Config file is located in:
World of Warcraft\_retail_\WTF\Account\ACCOUNTNAME\SavedVariables\VocalRaidAssistant.lua

**Comment by nanjuekaien1** [comment]
Netizens came to me and reported that some of his DH and DK skills did not work. I tested with my account and found that DEMONHUNTER's [317009] did not work either.
[VocalRaidAssistant.zip](https://github.com/Nitrak/Vocal-Raid-Assistant/files/9592756/VocalRaidAssistant.zip)

**Comment by nanjuekaien1** [comment]
Attached: Battle Log
9/18 07:54:33.325  SPELL_CAST_SUCCESS,Player-916-043F2647,"枫聖御雷-暗影之月",0x511,0x0,Creature-0-3120-2222-773-175456-0001A5ADEB,"群攻训练假人",0x10a28,0x0,317009,"罪孽烙印",0x20,Player-916-043F2647,0000000000000000,88120,88120,2933,306,964,0,17,55,120,0,-1921.24,7616.09,1699,4.5780,301
9/18 07:54:33.325  SPELL_AURA_APPLIED,Player-916-043F2647,"枫聖御雷-暗影之月",0x511,0x0,Creature-0-3120-2222-773-175456-0001A5ADEB,"群攻训练假人",0x10a28,0x0,317009,"罪孽烙印",0x20,DEBUFF
