### ISSUE TITLE
Missing Soothe, Tranq shot and shiv

### ISSUE THREAD

**Issue by Nitrak** [Nitrak/Vocal-Raid-Assistant#183]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/10738716/208736096-3fe01b3a-fe5e-4823-bf0a-27f6f884c448.png">

**Comment by Nitrak** [comment]
They were indeed missing.

**Comment by nyy23** [comment]
Shiv: 5938
Soothe: 2908
Tranquilizing Shot: 19801

**Comment by nyy23** [comment]
fixed with 3.0.4
