### ISSUE TITLE
Update broke settings

### ISSUE THREAD

**Issue by sausje** [Nitrak/Vocal-Raid-Assistant#219]
Today's update broke settings, can't access it anymore.

`4x ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:1854: AceConfigRegistry-3.0-21:ValidateOptionsTable(): VocalRaidAssistantConfig.args.generalOptions.args.minimapIcon: expected a table, got a boolean
[string "=[C]"]: ?
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:50: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:45>
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:224: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:255: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:220>
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:283: in function `ValidateOptionsTable'
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:325: in function `app'
[string "@Atlas/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1854: in function `Open'
[string "@VocalRaidAssistant/VocalRaidAssistant.lua"]:136: in function `?'
[string "@ACU/Libs/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@FrameXML/ChatFrame.lua"]:4933: in function <FrameXML/ChatFrame.lua:4879>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4596: in function <FrameXML/ChatFrame.lua:4595>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4632: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals:
(*temporary) = "AceConfigRegistry-3.0:ValidateOptionsTable(): VocalRaidAssistantConfig.args.generalOptions.args.minimapIcon: expected a table, got a boolean"
`

**Comment by Nitrak** [comment]
What version are you on, normal or the alpha version?

**Comment by sausje** [comment]
VocalRaidAssistant-3.3.1-a-wrath.zip through curseforge client auto updating.

**Comment by Nitrak** [comment]
Ah, it might be a Wrath specific bug then.
Can you try updating to this Alpha version and see if the issue persists?
https://legacy.curseforge.com/wow/addons/vocalraidassistant/files/4563939

**Comment by sausje** [comment]
> Ah, it might be a Wrath specific bug then. Can you try updating to this Alpha version and see if the issue persists? https://legacy.curseforge.com/wow/addons/vocalraidassistant/files/4563939

Yeah the alpha does fix this issue. Thanks for the quick response, in middle of raid so that helps :P
