### ISSUE TITLE
fortifying brew - wrong spell id

### ISSUE THREAD

**Issue by nyy23** [Nitrak/Vocal-Raid-Assistant#28]
Is: 115203
Shoud be: 243435

you need to change soundfile names too

**Comment by RishiKumarRay** [comment]
How to do this? i understood changing soundfile name  but didn't got first part

**Comment by nyy23** [comment]
We keep track of all spell ids we want to watch for in spellList lua file. Thats where the spell id got messed up.

**Comment by RishiKumarRay** [comment]
@nyy23 can you please review this changes #29

**Comment by RishiKumarRay** [comment]
@nyy23 I was renaming the files, there are more than 2 sound files since two files cannot have same name what sould i do?

**Comment by nyy23** [comment]
Mb,
Closing this issue because:

#115203 = BM,
#243435 = MW, WW

Will add 243435 in #36

**Comment by RishiKumarRay** [comment]
@nyy23 I am about to generate PR
