### ISSUE TITLE
Hex spell not always working

### ISSUE THREAD

**Issue by Nitrak** [Nitrak/Vocal-Raid-Assistant#52]
From user

"Hex issnt working if u take another Hex Variants. idk if u can change that.

Here are the IDs: 210873, 269352"

**Comment by nyy23** [comment]
This might also apply for other spells with same id. Plz look for a general solution to address this - Do not add the same id to spell list.

**Comment by nyy23** [comment]
This books change the spell id of hex: https://www.wowhead.com/search?q=Tome%20of%20Hex
Same should apply for mage sheep

**Comment by nyy23** [comment]
Just my idea how I would fix this:
https://github.com/Nitrak/Vocal-Raid-Assistant/tree/VRA-52-hex-and-polymorph

**Comment by Nitrak** [comment]
> Just my idea how I would fix this: https://github.com/Nitrak/Vocal-Raid-Assistant/tree/VRA-52-hex-and-polymorph

I just assigned myself so I had something to look at :P - This fix looks good, I just have one question about the code, but I will put it up as a PR and ask it there.
